[build]
  command = "" # the command you run to build this file
  functions = "src" # netlify-lambda builds to this folder AND Netlify reads functions from here
  publish = "server/static"
[functions]
  external_node_modules = [express]
