[build]
  command = "" # the command you run to build this file
  functions = "functions" # netlify-lambda builds to this folder AND Netlify reads functions from here
  publish = "static"
[functions]
  node_bundler = "esbuild"
  included_files = ["src/schema/schema.graphql"]
[dev]
  functions = "functions"
  functionsPort = 3001
[[headers]]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://nuxt-ff-test-task.netlify.app"
