[build]
  command = "yarn build:server" # the command you run to build this file
  functions = "server/src" # netlify-lambda builds to this folder AND Netlify reads functions from here
  publish = "server/static"
