query getTransactions($offset: Int, $limit: Int) {
  transactions(offset: $offset, limit: $limit) {
    amount
    currency
    reference
    category {
      name
      color
    }
    date
    account {
      id
      name
      bank {
        id
      }
    }
  }
}
