query getTransactions($cursorId: String, $limit: Int, $sortBy: String, $sortOrder: Sort) {
  transactions(cursorId: $cursorId, limit: $limit, sortBy: $sortBy, sortOrder: $sortOrder) {
    id
    amount
    currency
    reference
    category {
      name
      color
    }
    date
    account {
      id
      name
      bank {
        id
      }
    }
  }
}
query getTransactionsCount {
  totalTransactionsCount
}
