query getTransactions($cursorId: ID, $limit: Int, $sortBy: String, $sortOrder: Sort, $bankId: ID, $accountId: ID, $search: String, $dateFrom: DateTime, $dateTo: DateTime) {
  transactions(transactionsInput: { cursorId: $cursorId, limit: $limit, sortBy: $sortBy, sortOrder: $sortOrder, bankId: $bankId, accountId: $accountId, search: $search, dateFrom: $dateFrom, dateTo: $dateTo }) {
    id
    amount
    currency
    reference
    category {
      name
      color
    }
    date
    account {
      id
      name
      bank {
        id
      }
    }
  }
}
query getTransactionsCount($accountId: ID, $search: String, $dateFrom: DateTime, $dateTo: DateTime) {
  totalTransactionsCount(accountId: $accountId, search: $search, dateFrom: $dateFrom, dateTo: $dateTo)
}
